version : "3.8"
services:

  discovery:
    image: consul:1.14
    container_name: consul-server1
    restart: unless-stopped
    ports:
        - 8500:8500

    command: consul agent -server -dev -client 0.0.0.0 -bootstrap-expect=1 -data-dir=/consul/data -ui
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network
  consul:
    driver: bridge
