version : "3.9"

x-common-variables: &env-variables
  rootuser: 'Asa'
  rootpass: 'FavRwReB2lnuleS9'

services:
  gateway-service:
    container_name: gateway-service
    restart: unless-stopped
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '8888:4444'
    environment:
      <<: *env-variables

  authentication-service:
    container_name: authentication-service
    depends_on:
      - gateway-service
    restart: unless-stopped
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '81:6666'
    environment:
      <<: *env-variables

  account-service:
    container_name: account-service
    depends_on:
      - authentication-service
    restart: unless-stopped
    build:
      context: ./account-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '82:7777'
    environment:
      <<: *env-variables

  config-service:
    container_name: config-service
    depends_on:
      - gateway-service
    restart: unless-stopped
    build:
      context: ./config-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '83:5555'
    environment:
      <<: *env-variables


  statement-service:
    container_name: statement-service
    depends_on:
      - account-service
    restart: unless-stopped
    build:
      context: ./statement-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '84:3333'
    environment:
      <<: *env-variables

  transaction-service:
    container_name: transaction-service
    depends_on:
      - account-service
    restart: unless-stopped
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - '85:2222'
    environment:
      <<: *env-variables

volumes:
  PP3: